## Training and Test

In [12]:
import tensorflow as tf

In [17]:
x_data=[[1,2,1], [1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data=[[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [22]:
x_test=[[2,1,1],[3,1,2],[3,3,4]]
y_test=[[0,0,1],[0,0,1],[0,0,1]]

In [23]:
X=tf.placeholder("float", [None, 3])
Y=tf.placeholder("float", [None, 3])
w=tf.Variable(tf.random_normal([3, 3]))
b=tf.Variable(tf.random_normal([3]))

In [24]:
hypothesis = tf.nn.softmax(tf.matmul(X, w)+b)
#minimize cost
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

### Learning rate
* Overshooting(Big learning rate)
<br/>___=>cost가 nan으로 표시___
* Local minima(Small learning rate)
<br/>___=>cost가 변하지 않음___

### Correct prediction Test model

In [25]:
prediction = tf.arg_max(hypothesis, 1)
#arg_max -> one-hot
#가설과 실제값의 one-hot결과가 동일한지 확인
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [26]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _=sess.run([cost, w, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    print("Prediction:",sess.run(prediction, feed_dict={X: x_test}))
    #Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 11.081877 [[-0.8600547  -1.1630306   1.5413995 ]
 [ 1.3083875  -1.194714   -0.12660027]
 [-1.6276698  -1.0694296   0.2905276 ]]
1 7.4258857 [[-0.83618903 -1.1255482   1.4800515 ]
 [ 1.4666743  -1.0197507  -0.45985028]
 [-1.4679971  -0.8819493  -0.05662543]]
2 4.3004217 [[-0.83958167 -1.0881532   1.4460492 ]
 [ 1.4641058  -0.8449852  -0.6320473 ]
 [-1.4423832  -0.69460255 -0.26958603]]
3 3.140328 [[-0.8682642  -1.0511122   1.4376906 ]
 [ 1.325258   -0.67110384 -0.66708076]
 [-1.5478668  -0.5081511  -0.35055384]]
4 2.0961103 [[-0.8891284  -1.0156047   1.4230474 ]
 [ 1.2244217  -0.50206184 -0.7352865 ]
 [-1.6172278  -0.32723308 -0.4621109 ]]
5 1.21798 [[-0.9054444  -0.99178845  1.4155471 ]
 [ 1.1487808  -0.3831358  -0.7785716 ]
 [-1.6623358  -0.20249537 -0.54174066]]
6 1.0038028 [[-0.90635836 -0.99750173  1.4221745 ]
 [ 1.1658804  -0.41014242 -0.7686646 ]
 [-1.6181812  -0.23337838 -0.55501217]]
7 0.9849644 [[-0.91406107 -0.9949059   1.4272814 ]
 [ 1.1429603  -0.39234236 -0.76354456]
 [-

89 0.62845844 [[-1.244478   -1.0523423   1.8151338 ]
 [ 0.40947878 -0.12601286 -0.29639244]
 [-0.6926646  -0.48366523 -1.2302418 ]]
90 0.6267737 [[-1.2478715  -1.0527153   1.8189003 ]
 [ 0.40425396 -0.12370722 -0.29347324]
 [-0.68583965 -0.48582858 -1.2349033 ]]
91 0.6251243 [[-1.2512661  -1.0530763   1.8226559 ]
 [ 0.39911592 -0.12144364 -0.29059878]
 [-0.67910904 -0.4879523  -1.2395103 ]]
92 0.6235094 [[-1.254662   -1.0534252   1.8264008 ]
 [ 0.3940642  -0.11922198 -0.2877687 ]
 [-0.6724718  -0.4900366  -1.2440631 ]]
93 0.6219282 [[-1.2580594  -1.053762    1.830135  ]
 [ 0.38909793 -0.11704183 -0.28498256]
 [-0.6659274  -0.49208164 -1.2485625 ]]
94 0.62038004 [[-1.2614584  -1.0540868   1.8338587 ]
 [ 0.3842167  -0.11490312 -0.28224003]
 [-0.6594748  -0.4940878  -1.253009  ]]
95 0.61886394 [[-1.2648591  -1.0543996   1.8375722 ]
 [ 0.37941968 -0.11280543 -0.2795407 ]
 [-0.65311325 -0.4960552  -1.257403  ]]
96 0.6173792 [[-1.2682617  -1.0547005   1.8412757 ]
 [ 0.3747063  -0.11074863 -0

180 0.5489525 [[-1.5596069  -1.0476922   2.125613  ]
 [ 0.18694964 -0.03465071 -0.16522522]
 [-0.34011084 -0.57041174 -1.4960492 ]]
181 0.5484297 [[-1.5630606  -1.0473613   2.1287358 ]
 [ 0.1861979  -0.03435768 -0.16476652]
 [-0.33801973 -0.5707218  -1.4978302 ]]
182 0.5479095 [[-1.5665122  -1.0470271   2.131853  ]
 [ 0.18546315 -0.03406999 -0.16431944]
 [-0.33594725 -0.5710272  -1.4995972 ]]
183 0.547392 [[-1.5699615  -1.0466899   2.1349652 ]
 [ 0.1847452  -0.03378771 -0.16388376]
 [-0.33389273 -0.57132834 -1.5013506 ]]
184 0.546877 [[-1.5734086  -1.0463495   2.1380718 ]
 [ 0.1840435  -0.03351047 -0.16345927]
 [-0.331856   -0.5716251  -1.5030906 ]]
185 0.54636455 [[-1.5768533  -1.0460062   2.1411731 ]
 [ 0.1833578  -0.03323833 -0.16304572]
 [-0.32983655 -0.5719179  -1.5048172 ]]
186 0.54585457 [[-1.5802956  -1.0456599   2.144269  ]
 [ 0.18268764 -0.03297092 -0.16264294]
 [-0.32783407 -0.5722067  -1.5065309 ]]
187 0.54534686 [[-1.5837353  -1.0453106   2.1473596 ]
 [ 0.18203273 -0.03270