## Normalization
data값이 크거나 크기가 들쭉날쭉 할 때 필요

In [30]:
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [31]:
#Non-narmalized inputs
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

### Normalized inputs(Scaler사용)
* StandardScaler : 기본 스케일, 평균과 표준편차 사용
* MinMaxScaler : 최대/최소값이 각각 1, 0이 되도록 스케일링, 모든 feature값들이 0~1사이에 있도록 데이터를 재조정
* MaxAbsScaler : 최대절대값과 0이 각각 1, 0 이 되도록 스케일링, -1~1 사이로 재조정
* RobustScaler : 중앙값과 IQR(interquartile range)사용, 아웃라이어의 영향을 최소화

In [32]:
#xy = MinMaxScaler(xy)
#print(xy)

In [33]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    #noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [35]:
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [36]:
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [37]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [38]:
hypothesis = tf.matmul(X, w) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [39]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost : ", cost_val, "\nPrediction : \n", hy_val)

0 Cost :  3.0087461 
Prediction : 
 [[-0.97728443]
 [-0.8667579 ]
 [-1.1646266 ]
 [-1.425256  ]
 [-1.3242097 ]
 [-1.193039  ]
 [-1.602577  ]
 [-1.1607642 ]]
1 Cost :  3.0085254 
Prediction : 
 [[-0.9771991]
 [-0.8666748]
 [-1.164557 ]
 [-1.4252012]
 [-1.3241453]
 [-1.1929767]
 [-1.602534 ]
 [-1.160722 ]]
2 Cost :  3.0083046 
Prediction : 
 [[-0.97711384]
 [-0.86659175]
 [-1.1644871 ]
 [-1.4251463 ]
 [-1.3240812 ]
 [-1.1929145 ]
 [-1.6024911 ]
 [-1.1606798 ]]
3 Cost :  3.008084 
Prediction : 
 [[-0.9770285]
 [-0.8665088]
 [-1.1644175]
 [-1.4250915]
 [-1.3240168]
 [-1.1928523]
 [-1.6024482]
 [-1.1606376]]
4 Cost :  3.0078635 
Prediction : 
 [[-0.97694325]
 [-0.86642575]
 [-1.1643476 ]
 [-1.4250368 ]
 [-1.3239526 ]
 [-1.1927902 ]
 [-1.6024053 ]
 [-1.1605954 ]]
5 Cost :  3.0076427 
Prediction : 
 [[-0.9768579]
 [-0.8663427]
 [-1.1642778]
 [-1.4249821]
 [-1.3238883]
 [-1.192728 ]
 [-1.6023624]
 [-1.1605532]]
6 Cost :  3.007422 
Prediction : 
 [[-0.97677267]
 [-0.8662597 ]
 [-1.1642079 ]
 [-

83 Cost :  2.9904723 
Prediction : 
 [[-0.9702128]
 [-0.8598728]
 [-1.15884  ]
 [-1.4207097]
 [-1.3188785]
 [-1.1878818]
 [-1.5990157]
 [-1.1572618]]
84 Cost :  2.9902525 
Prediction : 
 [[-0.9701277]
 [-0.85979  ]
 [-1.1587701]
 [-1.420655 ]
 [-1.3188143]
 [-1.1878197]
 [-1.5989728]
 [-1.1572198]]
85 Cost :  2.990033 
Prediction : 
 [[-0.9700426 ]
 [-0.85970724]
 [-1.1587005 ]
 [-1.4206002 ]
 [-1.31875   ]
 [-1.1877575 ]
 [-1.5989299 ]
 [-1.1571776 ]]
86 Cost :  2.9898133 
Prediction : 
 [[-0.9699575]
 [-0.8596243]
 [-1.1586308]
 [-1.4205456]
 [-1.3186858]
 [-1.1876955]
 [-1.598887 ]
 [-1.1571354]]
87 Cost :  2.989594 
Prediction : 
 [[-0.96987236]
 [-0.8595415 ]
 [-1.1585612 ]
 [-1.4204907 ]
 [-1.3186219 ]
 [-1.1876335 ]
 [-1.5988442 ]
 [-1.1570932 ]]
88 Cost :  2.9893742 
Prediction : 
 [[-0.96978724]
 [-0.8594587 ]
 [-1.1584914 ]
 [-1.420436  ]
 [-1.3185575 ]
 [-1.1875713 ]
 [-1.5988013 ]
 [-1.157051  ]]
89 Cost :  2.9891543 
Prediction : 
 [[-0.9697021]
 [-0.8593758]
 [-1.1584218]

160 Cost :  2.9736297 
Prediction : 
 [[-0.96367645]
 [-0.85350794]
 [-1.1534898 ]
 [-1.4165068 ]
 [-1.31395   ]
 [-1.1831138 ]
 [-1.5957226 ]
 [-1.1540226 ]]
161 Cost :  2.9734116 
Prediction : 
 [[-0.9635917 ]
 [-0.85342526]
 [-1.1534204 ]
 [-1.4164522 ]
 [-1.3138859 ]
 [-1.1830521 ]
 [-1.5956799 ]
 [-1.1539805 ]]
162 Cost :  2.9731932 
Prediction : 
 [[-0.9635068]
 [-0.8533428]
 [-1.153351 ]
 [-1.4163976]
 [-1.313822 ]
 [-1.1829902]
 [-1.5956371]
 [-1.1539385]]
163 Cost :  2.972975 
Prediction : 
 [[-0.96342206]
 [-0.8532601 ]
 [-1.1532815 ]
 [-1.4163431 ]
 [-1.313758  ]
 [-1.1829283 ]
 [-1.5955944 ]
 [-1.1538965 ]]
164 Cost :  2.9727566 
Prediction : 
 [[-0.9633372]
 [-0.8531775]
 [-1.1532121]
 [-1.4162885]
 [-1.3136941]
 [-1.1828663]
 [-1.5955516]
 [-1.1538544]]
165 Cost :  2.9725387 
Prediction : 
 [[-0.9632524 ]
 [-0.85309494]
 [-1.1531427 ]
 [-1.416234  ]
 [-1.3136301 ]
 [-1.1828046 ]
 [-1.5955089 ]
 [-1.1538124 ]]
166 Cost :  2.9723203 
Prediction : 
 [[-0.96316755]
 [-0.85301

241 Cost :  2.956008 
Prediction : 
 [[-0.9568155 ]
 [-0.84682834]
 [-1.1478755 ]
 [-1.4120958 ]
 [-1.3087777 ]
 [-1.1781105 ]
 [-1.5922676 ]
 [-1.1506245 ]]
242 Cost :  2.955791 
Prediction : 
 [[-0.95673096]
 [-0.84674597]
 [-1.1478064 ]
 [-1.4120415 ]
 [-1.3087139 ]
 [-1.1780488 ]
 [-1.5922251 ]
 [-1.1505826 ]]
243 Cost :  2.9555743 
Prediction : 
 [[-0.95664644]
 [-0.84666365]
 [-1.1477371 ]
 [-1.4119871 ]
 [-1.3086503 ]
 [-1.1779872 ]
 [-1.5921824 ]
 [-1.1505407 ]]
244 Cost :  2.9553576 
Prediction : 
 [[-0.9565619 ]
 [-0.84658146]
 [-1.1476679 ]
 [-1.411933  ]
 [-1.3085865 ]
 [-1.1779256 ]
 [-1.5921398 ]
 [-1.1504989 ]]
245 Cost :  2.9551406 
Prediction : 
 [[-0.9564774]
 [-0.8464991]
 [-1.1475987]
 [-1.4118785]
 [-1.3085227]
 [-1.1778638]
 [-1.5920972]
 [-1.1504569]]
246 Cost :  2.9549239 
Prediction : 
 [[-0.9563929]
 [-0.8464169]
 [-1.1475296]
 [-1.411824 ]
 [-1.308459 ]
 [-1.1778022]
 [-1.5920546]
 [-1.1504151]]
247 Cost :  2.9547071 
Prediction : 
 [[-0.95630836]
 [-0.846334

332 Cost :  2.9363508 
Prediction : 
 [[-0.94913983]
 [-0.83935374]
 [-1.1415924 ]
 [-1.4071591 ]
 [-1.3029892 ]
 [-1.1725109 ]
 [-1.5883988 ]
 [-1.1468192 ]]
333 Cost :  2.9361358 
Prediction : 
 [[-0.9490557 ]
 [-0.83927184]
 [-1.1415235 ]
 [-1.407105  ]
 [-1.3029258 ]
 [-1.1724494 ]
 [-1.5883564 ]
 [-1.1467774 ]]
334 Cost :  2.9359205 
Prediction : 
 [[-0.9489715]
 [-0.8391898]
 [-1.1414545]
 [-1.4070507]
 [-1.3028623]
 [-1.1723878]
 [-1.5883139]
 [-1.1467357]]
335 Cost :  2.9357052 
Prediction : 
 [[-0.9488872]
 [-0.8391078]
 [-1.1413856]
 [-1.4069966]
 [-1.3027987]
 [-1.1723263]
 [-1.5882715]
 [-1.146694 ]]
336 Cost :  2.9354897 
Prediction : 
 [[-0.94880295]
 [-0.8390257 ]
 [-1.1413167 ]
 [-1.4069424 ]
 [-1.3027352 ]
 [-1.172265  ]
 [-1.5882291 ]
 [-1.1466522 ]]
337 Cost :  2.9352746 
Prediction : 
 [[-0.9487188]
 [-0.8389438]
 [-1.1412477]
 [-1.4068882]
 [-1.3026717]
 [-1.1722035]
 [-1.5881866]
 [-1.1466105]]
338 Cost :  2.9350593 
Prediction : 
 [[-0.9486346 ]
 [-0.83886176]
 [

395 Cost :  2.9228125 
Prediction : 
 [[-0.94383657]
 [-0.83419055]
 [-1.1372522 ]
 [-1.4037489 ]
 [-1.2989907 ]
 [-1.1686428 ]
 [-1.5857271 ]
 [-1.1441914 ]]
396 Cost :  2.9225981 
Prediction : 
 [[-0.9437525 ]
 [-0.83410877]
 [-1.1371834 ]
 [-1.4036949 ]
 [-1.2989274 ]
 [-1.1685815 ]
 [-1.5856848 ]
 [-1.1441498 ]]
397 Cost :  2.9223838 
Prediction : 
 [[-0.9436685]
 [-0.8340269]
 [-1.1371148]
 [-1.4036407]
 [-1.2988641]
 [-1.1685202]
 [-1.5856425]
 [-1.1441082]]
398 Cost :  2.9221697 
Prediction : 
 [[-0.9435843]
 [-0.8339451]
 [-1.137046 ]
 [-1.4035869]
 [-1.2988007]
 [-1.1684588]
 [-1.5856001]
 [-1.1440666]]
399 Cost :  2.921955 
Prediction : 
 [[-0.9435003]
 [-0.8338632]
 [-1.1369771]
 [-1.4035327]
 [-1.2987373]
 [-1.1683975]
 [-1.5855578]
 [-1.144025 ]]
400 Cost :  2.921741 
Prediction : 
 [[-0.94341624]
 [-0.8337814 ]
 [-1.1369083 ]
 [-1.4034787 ]
 [-1.2986739 ]
 [-1.1683362 ]
 [-1.5855155 ]
 [-1.1439834 ]]
401 Cost :  2.9215267 
Prediction : 
 [[-0.9433322]
 [-0.8336994]
 [-1.1

537 Cost :  2.8925524 
Prediction : 
 [[-0.9319391]
 [-0.8226055]
 [-1.1275136]
 [-1.3960966]
 [-1.2900187]
 [-1.1599631]
 [-1.5797305]
 [-1.1382934]]
538 Cost :  2.8923402 
Prediction : 
 [[-0.93185556]
 [-0.82252413]
 [-1.1274452 ]
 [-1.3960428 ]
 [-1.2899556 ]
 [-1.1599021 ]
 [-1.5796883 ]
 [-1.1382519 ]]
539 Cost :  2.892128 
Prediction : 
 [[-0.9317719 ]
 [-0.82244265]
 [-1.1273767 ]
 [-1.3959891 ]
 [-1.2898926 ]
 [-1.1598412 ]
 [-1.5796461 ]
 [-1.1382104 ]]
540 Cost :  2.891916 
Prediction : 
 [[-0.9316882 ]
 [-0.82236123]
 [-1.1273084 ]
 [-1.3959353 ]
 [-1.2898295 ]
 [-1.1597801 ]
 [-1.579604  ]
 [-1.138169  ]]
541 Cost :  2.891704 
Prediction : 
 [[-0.9316046]
 [-0.8222799]
 [-1.12724  ]
 [-1.3958814]
 [-1.2897664]
 [-1.1597191]
 [-1.579562 ]
 [-1.1381276]]
542 Cost :  2.891492 
Prediction : 
 [[-0.93152106]
 [-0.82219845]
 [-1.1271715 ]
 [-1.3958278 ]
 [-1.2897034 ]
 [-1.1596582 ]
 [-1.5795197 ]
 [-1.1380861 ]]
543 Cost :  2.8912797 
Prediction : 
 [[-0.9314374]
 [-0.8221171]


 [-1.134034  ]]
641 Cost :  2.8705902 
Prediction : 
 [[-0.92326283]
 [-0.81415796]
 [-1.1204123 ]
 [-1.3905165 ]
 [-1.2834762 ]
 [-1.1536341 ]
 [-1.5753579 ]
 [-1.1339928 ]]
642 Cost :  2.8703794 
Prediction : 
 [[-0.92317975]
 [-0.8140771 ]
 [-1.1203442 ]
 [-1.390463  ]
 [-1.2834134 ]
 [-1.1535733 ]
 [-1.575316  ]
 [-1.1339514 ]]
643 Cost :  2.8701692 
Prediction : 
 [[-0.92309654]
 [-0.81399584]
 [-1.120276  ]
 [-1.3904095 ]
 [-1.2833507 ]
 [-1.1535125 ]
 [-1.575274  ]
 [-1.1339102 ]]
644 Cost :  2.869959 
Prediction : 
 [[-0.9230133 ]
 [-0.81391495]
 [-1.120208  ]
 [-1.3903558 ]
 [-1.283288  ]
 [-1.1534519 ]
 [-1.575232  ]
 [-1.1338689 ]]
645 Cost :  2.869749 
Prediction : 
 [[-0.92293024]
 [-0.8138339 ]
 [-1.1201398 ]
 [-1.3903024 ]
 [-1.2832252 ]
 [-1.1533911 ]
 [-1.5751901 ]
 [-1.1338276 ]]
646 Cost :  2.8695388 
Prediction : 
 [[-0.92284703]
 [-0.8137529 ]
 [-1.1200718 ]
 [-1.3902488 ]
 [-1.2831624 ]
 [-1.1533306 ]
 [-1.5751481 ]
 [-1.1337863 ]]
647 Cost :  2.8693285 
Predictio

735 Cost :  2.8508935 
Prediction : 
 [[-0.9154537 ]
 [-0.80655396]
 [-1.1140199 ]
 [-1.3854928 ]
 [-1.2775865 ]
 [-1.1479363 ]
 [-1.5714207 ]
 [-1.1301205 ]]
736 Cost :  2.8506846 
Prediction : 
 [[-0.9153707]
 [-0.8064733]
 [-1.1139518]
 [-1.3854394]
 [-1.2775239]
 [-1.1478758]
 [-1.5713788]
 [-1.1300793]]
737 Cost :  2.8504758 
Prediction : 
 [[-0.91528773]
 [-0.80639243]
 [-1.113884  ]
 [-1.385386  ]
 [-1.2774613 ]
 [-1.1478152 ]
 [-1.571337  ]
 [-1.1300381 ]]
738 Cost :  2.850267 
Prediction : 
 [[-0.91520464]
 [-0.80631167]
 [-1.113816  ]
 [-1.3853326 ]
 [-1.2773987 ]
 [-1.1477547 ]
 [-1.5712951 ]
 [-1.129997  ]]
739 Cost :  2.8500578 
Prediction : 
 [[-0.9151217]
 [-0.8062308]
 [-1.1137481]
 [-1.3852792]
 [-1.2773361]
 [-1.1476942]
 [-1.5712533]
 [-1.1299559]]
740 Cost :  2.849849 
Prediction : 
 [[-0.9150387]
 [-0.80615  ]
 [-1.1136801]
 [-1.3852258]
 [-1.2772737]
 [-1.1476336]
 [-1.5712115]
 [-1.1299148]]
741 Cost :  2.8496401 
Prediction : 
 [[-0.91495574]
 [-0.8060692 ]
 [-1

840 Cost :  2.8290563 
Prediction : 
 [[-0.9067626]
 [-0.7980913]
 [-1.1069055]
 [-1.3799019]
 [-1.2710319]
 [-1.1415954]
 [-1.5670388]
 [-1.1258104]]
841 Cost :  2.828849 
Prediction : 
 [[-0.9066801 ]
 [-0.79801095]
 [-1.1068377 ]
 [-1.3798487 ]
 [-1.2709696 ]
 [-1.141535  ]
 [-1.5669972 ]
 [-1.1257694 ]]
842 Cost :  2.828642 
Prediction : 
 [[-0.9065975]
 [-0.7979305]
 [-1.1067703]
 [-1.3797956]
 [-1.2709072]
 [-1.1414747]
 [-1.5669554]
 [-1.1257284]]
843 Cost :  2.8284347 
Prediction : 
 [[-0.9065149]
 [-0.7978501]
 [-1.1067026]
 [-1.3797424]
 [-1.2708449]
 [-1.1414144]
 [-1.5669138]
 [-1.1256874]]
844 Cost :  2.8282275 
Prediction : 
 [[-0.9064323]
 [-0.7977696]
 [-1.106635 ]
 [-1.3796892]
 [-1.2707827]
 [-1.1413542]
 [-1.5668721]
 [-1.1256464]]
845 Cost :  2.8280203 
Prediction : 
 [[-0.90634966]
 [-0.7976893 ]
 [-1.1065674 ]
 [-1.379636  ]
 [-1.2707202 ]
 [-1.1412939 ]
 [-1.5668304 ]
 [-1.1256055 ]]
846 Cost :  2.8278134 
Prediction : 
 [[-0.90626717]
 [-0.79760885]
 [-1.1064998

940 Cost :  2.8084185 
Prediction : 
 [[-0.8985169]
 [-0.7900628]
 [-1.1001557]
 [-1.374597 ]
 [-1.2648128]
 [-1.1355791]
 [-1.5628811]
 [-1.1217217]]
941 Cost :  2.8082128 
Prediction : 
 [[-0.89843464]
 [-0.7899827 ]
 [-1.1000884 ]
 [-1.374544  ]
 [-1.2647507 ]
 [-1.135519  ]
 [-1.5628395 ]
 [-1.1216809 ]]
942 Cost :  2.8080072 
Prediction : 
 [[-0.89835227]
 [-0.7899027 ]
 [-1.1000209 ]
 [-1.374491  ]
 [-1.2646887 ]
 [-1.1354591 ]
 [-1.562798  ]
 [-1.12164   ]]
943 Cost :  2.8078017 
Prediction : 
 [[-0.89827  ]
 [-0.7898224]
 [-1.0999535]
 [-1.374438 ]
 [-1.2646266]
 [-1.1353989]
 [-1.5627565]
 [-1.1215992]]
944 Cost :  2.807596 
Prediction : 
 [[-0.89818776]
 [-0.7897423 ]
 [-1.0998862 ]
 [-1.3743851 ]
 [-1.2645645 ]
 [-1.135339  ]
 [-1.562715  ]
 [-1.1215583 ]]
945 Cost :  2.8073905 
Prediction : 
 [[-0.8981054]
 [-0.7896622]
 [-1.0998188]
 [-1.3743322]
 [-1.2645025]
 [-1.1352789]
 [-1.5626734]
 [-1.1215174]]
946 Cost :  2.8071847 
Prediction : 
 [[-0.8980231 ]
 [-0.78958195]
 [-

1033 Cost :  2.7893724 
Prediction : 
 [[-0.89087975]
 [-0.7826262 ]
 [-1.0939035 ]
 [-1.3696833 ]
 [-1.2590525 ]
 [-1.1300063 ]
 [-1.5590295 ]
 [-1.1179328 ]]
1034 Cost :  2.789168 
Prediction : 
 [[-0.89079785]
 [-0.78254634]
 [-1.0938363 ]
 [-1.3696305 ]
 [-1.2589905 ]
 [-1.1299465 ]
 [-1.558988  ]
 [-1.1178921 ]]
1035 Cost :  2.7889638 
Prediction : 
 [[-0.89071584]
 [-0.78246653]
 [-1.0937693 ]
 [-1.3695776 ]
 [-1.2589288 ]
 [-1.1298866 ]
 [-1.5589466 ]
 [-1.1178515 ]]
1036 Cost :  2.7887597 
Prediction : 
 [[-0.8906338 ]
 [-0.78238666]
 [-1.0937021 ]
 [-1.369525  ]
 [-1.2588669 ]
 [-1.1298268 ]
 [-1.5589052 ]
 [-1.1178107 ]]
1037 Cost :  2.7885556 
Prediction : 
 [[-0.8905519]
 [-0.7823069]
 [-1.0936351]
 [-1.3694723]
 [-1.258805 ]
 [-1.129767 ]
 [-1.5588639]
 [-1.1177701]]
1038 Cost :  2.7883515 
Prediction : 
 [[-0.8904699 ]
 [-0.78222704]
 [-1.0935678 ]
 [-1.3694195 ]
 [-1.2587432 ]
 [-1.1297071 ]
 [-1.5588225 ]
 [-1.1177294 ]]
1039 Cost :  2.7881474 
Prediction : 
 [[-0.89038

1088 Cost :  2.7781696 
Prediction : 
 [[-0.8863752]
 [-0.7782399]
 [-1.0902157]
 [-1.3667847]
 [-1.2556546]
 [-1.1267194]
 [-1.5567572]
 [-1.1156985]]
1089 Cost :  2.7779663 
Prediction : 
 [[-0.8862934]
 [-0.7781603]
 [-1.0901487]
 [-1.3667321]
 [-1.2555928]
 [-1.1266595]
 [-1.556716 ]
 [-1.1156579]]
1090 Cost :  2.777763 
Prediction : 
 [[-0.8862115]
 [-0.7780805]
 [-1.0900817]
 [-1.3666794]
 [-1.2555311]
 [-1.1265999]
 [-1.5566747]
 [-1.1156174]]
1091 Cost :  2.7775598 
Prediction : 
 [[-0.88612974]
 [-0.778001  ]
 [-1.0900148 ]
 [-1.3666267 ]
 [-1.2554693 ]
 [-1.1265402 ]
 [-1.5566335 ]
 [-1.1155767 ]]
1092 Cost :  2.7773566 
Prediction : 
 [[-0.88604784]
 [-0.77792126]
 [-1.0899479 ]
 [-1.366574  ]
 [-1.2554076 ]
 [-1.1264805 ]
 [-1.5565922 ]
 [-1.1155362 ]]
1093 Cost :  2.7771535 
Prediction : 
 [[-0.88596606]
 [-0.7778417 ]
 [-1.0898807 ]
 [-1.3665216 ]
 [-1.255346  ]
 [-1.1264209 ]
 [-1.556551  ]
 [-1.1154957 ]]
1094 Cost :  2.7769504 
Prediction : 
 [[-0.88588417]
 [-0.777761

1218 Cost :  2.7518773 
Prediction : 
 [[-0.8757657 ]
 [-0.76790947]
 [-1.0815302 ]
 [-1.3599579 ]
 [-1.2476519 ]
 [-1.1189773 ]
 [-1.5514059 ]
 [-1.1104349 ]]
1219 Cost :  2.751676 
Prediction : 
 [[-0.87568426]
 [-0.76783013]
 [-1.0814636 ]
 [-1.3599055 ]
 [-1.2475905 ]
 [-1.118918  ]
 [-1.5513649 ]
 [-1.1103945 ]]
1220 Cost :  2.7514749 
Prediction : 
 [[-0.87560284]
 [-0.767751  ]
 [-1.081397  ]
 [-1.3598533 ]
 [-1.247529  ]
 [-1.1188586 ]
 [-1.5513238 ]
 [-1.1103542 ]]
1221 Cost :  2.7512736 
Prediction : 
 [[-0.8755214 ]
 [-0.76767164]
 [-1.0813303 ]
 [-1.3598008 ]
 [-1.2474676 ]
 [-1.1187991 ]
 [-1.5512826 ]
 [-1.1103138 ]]
1222 Cost :  2.7510726 
Prediction : 
 [[-0.8754401 ]
 [-0.76759243]
 [-1.0812638 ]
 [-1.3597484 ]
 [-1.2474062 ]
 [-1.1187396 ]
 [-1.5512416 ]
 [-1.1102734 ]]
1223 Cost :  2.7508712 
Prediction : 
 [[-0.8753587]
 [-0.7675131]
 [-1.081197 ]
 [-1.3596959]
 [-1.247345 ]
 [-1.1186802]
 [-1.5512005]
 [-1.110233 ]]
1224 Cost :  2.75067 
Prediction : 
 [[-0.8752773

 [[-0.87137353]
 [-0.7636327 ]
 [-1.0779341 ]
 [-1.357131  ]
 [-1.2443383 ]
 [-1.1157718 ]
 [-1.5491894 ]
 [-1.1082555 ]]
1273 Cost :  2.7408292 
Prediction : 
 [[-0.87129223]
 [-0.7635537 ]
 [-1.0778676 ]
 [-1.3570788 ]
 [-1.244277  ]
 [-1.1157125 ]
 [-1.5491486 ]
 [-1.1082152 ]]
1274 Cost :  2.7406287 
Prediction : 
 [[-0.87121105]
 [-0.76347446]
 [-1.0778012 ]
 [-1.3570266 ]
 [-1.2442157 ]
 [-1.1156533 ]
 [-1.5491076 ]
 [-1.108175  ]]
1275 Cost :  2.7404284 
Prediction : 
 [[-0.8711299 ]
 [-0.76339537]
 [-1.0777347 ]
 [-1.3569742 ]
 [-1.2441545 ]
 [-1.115594  ]
 [-1.5490665 ]
 [-1.1081347 ]]
1276 Cost :  2.740228 
Prediction : 
 [[-0.87104857]
 [-0.7633164 ]
 [-1.0776682 ]
 [-1.356922  ]
 [-1.2440932 ]
 [-1.1155348 ]
 [-1.5490257 ]
 [-1.1080945 ]]
1277 Cost :  2.7400277 
Prediction : 
 [[-0.87096727]
 [-0.76323724]
 [-1.0776017 ]
 [-1.3568697 ]
 [-1.2440319 ]
 [-1.1154755 ]
 [-1.5489846 ]
 [-1.1080542 ]]
1278 Cost :  2.7398276 
Prediction : 
 [[-0.8708861 ]
 [-0.76315814]
 [-1.07753

 [-1.1055582 ]]
1340 Cost :  2.727439 
Prediction : 
 [[-0.8658582]
 [-0.7582619]
 [-1.0734184]
 [-1.3535813]
 [-1.2401774]
 [-1.1117463]
 [-1.5464064]
 [-1.1055179]]
1341 Cost :  2.7272391 
Prediction : 
 [[-0.86577713]
 [-0.75818294]
 [-1.073352  ]
 [-1.3535292 ]
 [-1.2401164 ]
 [-1.1116872 ]
 [-1.5463654 ]
 [-1.1054776 ]]
1342 Cost :  2.7270398 
Prediction : 
 [[-0.8656961]
 [-0.758104 ]
 [-1.0732857]
 [-1.353477 ]
 [-1.2400552]
 [-1.111628 ]
 [-1.5463245]
 [-1.1054373]]
1343 Cost :  2.7268405 
Prediction : 
 [[-0.865615  ]
 [-0.75802517]
 [-1.0732193 ]
 [-1.3534248 ]
 [-1.239994  ]
 [-1.1115689 ]
 [-1.5462836 ]
 [-1.1053971 ]]
1344 Cost :  2.7266407 
Prediction : 
 [[-0.86553395]
 [-0.7579462 ]
 [-1.073153  ]
 [-1.3533726 ]
 [-1.2399328 ]
 [-1.1115097 ]
 [-1.5462427 ]
 [-1.1053569 ]]
1345 Cost :  2.7264414 
Prediction : 
 [[-0.8654529]
 [-0.7578673]
 [-1.0730865]
 [-1.3533204]
 [-1.2398717]
 [-1.1114506]
 [-1.5462018]
 [-1.1053166]]
1346 Cost :  2.7262418 
Prediction : 
 [[-0.86537

 [[-0.85785043]
 [-0.75046515]
 [-1.0668626 ]
 [-1.3484279 ]
 [-1.2341368 ]
 [-1.1059027 ]
 [-1.5423663 ]
 [-1.1015446 ]]
1440 Cost :  2.7075734 
Prediction : 
 [[-0.8577697 ]
 [-0.75038654]
 [-1.0667965 ]
 [-1.3483759 ]
 [-1.2340759 ]
 [-1.1058438 ]
 [-1.5423255 ]
 [-1.1015046 ]]
1441 Cost :  2.7073755 
Prediction : 
 [[-0.857689  ]
 [-0.75030786]
 [-1.0667304 ]
 [-1.348324  ]
 [-1.234015  ]
 [-1.1057848 ]
 [-1.5422847 ]
 [-1.1014645 ]]
1442 Cost :  2.7071772 
Prediction : 
 [[-0.8576082 ]
 [-0.75022924]
 [-1.0666642 ]
 [-1.3482718 ]
 [-1.233954  ]
 [-1.1057258 ]
 [-1.542244  ]
 [-1.1014243 ]]
1443 Cost :  2.7069793 
Prediction : 
 [[-0.8575274]
 [-0.7501506]
 [-1.066598 ]
 [-1.3482199]
 [-1.2338932]
 [-1.1056669]
 [-1.5422032]
 [-1.1013843]]
1444 Cost :  2.7067811 
Prediction : 
 [[-0.8574467 ]
 [-0.75007194]
 [-1.0665319 ]
 [-1.3481679 ]
 [-1.2338321 ]
 [-1.105608  ]
 [-1.5421624 ]
 [-1.1013441 ]]
1445 Cost :  2.7065833 
Prediction : 
 [[-0.85736597]
 [-0.7499933 ]
 [-1.0664659 ]
 [

1522 Cost :  2.6914043 
Prediction : 
 [[-0.8511647]
 [-0.7439543]
 [-1.061388 ]
 [-1.3441243]
 [-1.2290925]
 [-1.1010225]
 [-1.5389916]
 [-1.0982254]]
1523 Cost :  2.6912074 
Prediction : 
 [[-0.85108423]
 [-0.743876  ]
 [-1.0613221 ]
 [-1.3440725 ]
 [-1.2290317 ]
 [-1.1009637 ]
 [-1.5389509 ]
 [-1.0981853 ]]
1524 Cost :  2.6910107 
Prediction : 
 [[-0.85100377]
 [-0.74379754]
 [-1.0612564 ]
 [-1.3440206 ]
 [-1.228971  ]
 [-1.1009051 ]
 [-1.5389104 ]
 [-1.0981454 ]]
1525 Cost :  2.690814 
Prediction : 
 [[-0.8509233]
 [-0.7437192]
 [-1.0611905]
 [-1.3439689]
 [-1.2289102]
 [-1.1008463]
 [-1.5388697]
 [-1.0981054]]
1526 Cost :  2.6906176 
Prediction : 
 [[-0.85084283]
 [-0.743641  ]
 [-1.0611246 ]
 [-1.3439171 ]
 [-1.2288496 ]
 [-1.1007875 ]
 [-1.5388291 ]
 [-1.0980655 ]]
1527 Cost :  2.6904209 
Prediction : 
 [[-0.85076237]
 [-0.7435626 ]
 [-1.0610588 ]
 [-1.3438652 ]
 [-1.2287889 ]
 [-1.1007288 ]
 [-1.5387884 ]
 [-1.0980256 ]]
1528 Cost :  2.6902242 
Prediction : 
 [[-0.8506819 ]
 [-

1577 Cost :  2.6806083 
Prediction : 
 [[-0.84674203]
 [-0.73964846]
 [-1.0577674 ]
 [-1.3412781 ]
 [-1.2257564 ]
 [-1.097795  ]
 [-1.5367602 ]
 [-1.0960307 ]]
1578 Cost :  2.6804123 
Prediction : 
 [[-0.8466618 ]
 [-0.73957026]
 [-1.0577017 ]
 [-1.3412262 ]
 [-1.2256957 ]
 [-1.0977364 ]
 [-1.5367197 ]
 [-1.0959909 ]]
1579 Cost :  2.6802163 
Prediction : 
 [[-0.84658146]
 [-0.73949206]
 [-1.057636  ]
 [-1.3411746 ]
 [-1.225635  ]
 [-1.0976778 ]
 [-1.5366793 ]
 [-1.095951  ]]
1580 Cost :  2.6800206 
Prediction : 
 [[-0.8465011 ]
 [-0.73941374]
 [-1.0575703 ]
 [-1.341123  ]
 [-1.2255745 ]
 [-1.097619  ]
 [-1.5366387 ]
 [-1.0959111 ]]
1581 Cost :  2.6798248 
Prediction : 
 [[-0.8464209 ]
 [-0.73933566]
 [-1.0575044 ]
 [-1.3410714 ]
 [-1.225514  ]
 [-1.0975606 ]
 [-1.5365982 ]
 [-1.0958713 ]]
1582 Cost :  2.679629 
Prediction : 
 [[-0.84634054]
 [-0.73925745]
 [-1.0574387 ]
 [-1.3410196 ]
 [-1.2254534 ]
 [-1.097502  ]
 [-1.5365577 ]
 [-1.0958315 ]]
1583 Cost :  2.6794333 
Prediction : 
 [[

1639 Cost :  2.6684947 
Prediction : 
 [[-0.8417697]
 [-0.7348068]
 [-1.053696 ]
 [-1.3380771]
 [-1.2220047]
 [-1.0941656]
 [-1.5342501]
 [-1.0935624]]
1640 Cost :  2.6683 
Prediction : 
 [[-0.8416896]
 [-0.7347288]
 [-1.0536305]
 [-1.3380255]
 [-1.2219441]
 [-1.0941072]
 [-1.5342097]
 [-1.0935225]]
1641 Cost :  2.668105 
Prediction : 
 [[-0.8416096 ]
 [-0.73465085]
 [-1.0535649 ]
 [-1.3379738 ]
 [-1.2218838 ]
 [-1.0940487 ]
 [-1.5341692 ]
 [-1.0934827 ]]
1642 Cost :  2.66791 
Prediction : 
 [[-0.8415296 ]
 [-0.73457295]
 [-1.0534993 ]
 [-1.3379223 ]
 [-1.2218232 ]
 [-1.0939902 ]
 [-1.5341287 ]
 [-1.093443  ]]
1643 Cost :  2.667715 
Prediction : 
 [[-0.8414495 ]
 [-0.73449486]
 [-1.0534338 ]
 [-1.3378708 ]
 [-1.2217629 ]
 [-1.0939317 ]
 [-1.5340883 ]
 [-1.0934032 ]]
1644 Cost :  2.6675203 
Prediction : 
 [[-0.8413694 ]
 [-0.73441684]
 [-1.0533682 ]
 [-1.3378191 ]
 [-1.2217025 ]
 [-1.0938733 ]
 [-1.5340478 ]
 [-1.0933634 ]]
1645 Cost :  2.6673255 
Prediction : 
 [[-0.8412894]
 [-0.73433

1712 Cost :  2.6543145 
Prediction : 
 [[-0.83593476]
 [-0.7291241 ]
 [-1.0489178 ]
 [-1.3343203 ]
 [-1.2176015 ]
 [-1.089906  ]
 [-1.5313039 ]
 [-1.0906644 ]]
1713 Cost :  2.6541204 
Prediction : 
 [[-0.8358549]
 [-0.7290465]
 [-1.0488522]
 [-1.3342689]
 [-1.2175413]
 [-1.0898476]
 [-1.5312636]
 [-1.0906248]]
1714 Cost :  2.6539268 
Prediction : 
 [[-0.835775 ]
 [-0.7289686]
 [-1.0487869]
 [-1.3342175]
 [-1.2174811]
 [-1.0897892]
 [-1.5312233]
 [-1.0905851]]
1715 Cost :  2.6537333 
Prediction : 
 [[-0.83569515]
 [-0.728891  ]
 [-1.0487216 ]
 [-1.334166  ]
 [-1.2174208 ]
 [-1.089731  ]
 [-1.5311829 ]
 [-1.0905454 ]]
1716 Cost :  2.6535392 
Prediction : 
 [[-0.8356153]
 [-0.7288131]
 [-1.048656 ]
 [-1.3341147]
 [-1.2173605]
 [-1.0896726]
 [-1.5311426]
 [-1.0905058]]
1717 Cost :  2.6533456 
Prediction : 
 [[-0.8355354]
 [-0.7287355]
 [-1.0485907]
 [-1.3340633]
 [-1.2173003]
 [-1.0896144]
 [-1.5311023]
 [-1.0904661]]
1718 Cost :  2.6531518 
Prediction : 
 [[-0.83545554]
 [-0.7286576 ]
 [-

1771 Cost :  2.6428995 
Prediction : 
 [[-0.8312247]
 [-0.7245387]
 [-1.0450616]
 [-1.3312886]
 [-1.2140483]
 [-1.0864682]
 [-1.5289267]
 [-1.0883266]]
1772 Cost :  2.6427069 
Prediction : 
 [[-0.83114505]
 [-0.72446096]
 [-1.0449964 ]
 [-1.3312373 ]
 [-1.2139882 ]
 [-1.0864102 ]
 [-1.5288866 ]
 [-1.088287  ]]
1773 Cost :  2.6425138 
Prediction : 
 [[-0.8310653]
 [-0.7243834]
 [-1.044931 ]
 [-1.331186 ]
 [-1.213928 ]
 [-1.086352 ]
 [-1.5288464]
 [-1.0882475]]
1774 Cost :  2.6423209 
Prediction : 
 [[-0.83098555]
 [-0.7243057 ]
 [-1.0448658 ]
 [-1.3311346 ]
 [-1.2138679 ]
 [-1.0862938 ]
 [-1.5288062 ]
 [-1.088208  ]]
1775 Cost :  2.642128 
Prediction : 
 [[-0.8309059 ]
 [-0.72422814]
 [-1.0448005 ]
 [-1.3310833 ]
 [-1.2138078 ]
 [-1.0862355 ]
 [-1.5287659 ]
 [-1.0881684 ]]
1776 Cost :  2.641935 
Prediction : 
 [[-0.83082616]
 [-0.7241504 ]
 [-1.0447352 ]
 [-1.3310322 ]
 [-1.2137476 ]
 [-1.0861775 ]
 [-1.5287257 ]
 [-1.0881289 ]]
1777 Cost :  2.6417422 
Prediction : 
 [[-0.8307464]
 [-0.

1839 Cost :  2.6298156 
Prediction : 
 [[-0.825814  ]
 [-0.71926975]
 [-1.0406308 ]
 [-1.3278048 ]
 [-1.2099655 ]
 [-1.0825183 ]
 [-1.5261946 ]
 [-1.0856396 ]]
1840 Cost :  2.6296234 
Prediction : 
 [[-0.8257346]
 [-0.7191923]
 [-1.0405657]
 [-1.3277537]
 [-1.2099054]
 [-1.0824604]
 [-1.5261544]
 [-1.0856   ]]
1841 Cost :  2.6294317 
Prediction : 
 [[-0.8256551]
 [-0.719115 ]
 [-1.0405006]
 [-1.3277025]
 [-1.2098455]
 [-1.0824022]
 [-1.5261142]
 [-1.0855606]]
1842 Cost :  2.6292398 
Prediction : 
 [[-0.8255757]
 [-0.7190377]
 [-1.0404357]
 [-1.3276513]
 [-1.2097855]
 [-1.0823443]
 [-1.5260742]
 [-1.0855211]]
1843 Cost :  2.6290476 
Prediction : 
 [[-0.8254962]
 [-0.7189603]
 [-1.0403705]
 [-1.3276001]
 [-1.2097256]
 [-1.0822862]
 [-1.526034 ]
 [-1.0854815]]
1844 Cost :  2.628856 
Prediction : 
 [[-0.8254168 ]
 [-0.71888286]
 [-1.0403055 ]
 [-1.327549  ]
 [-1.2096655 ]
 [-1.0822283 ]
 [-1.5259938 ]
 [-1.0854421 ]]
1845 Cost :  2.628664 
Prediction : 
 [[-0.8253373 ]
 [-0.71880555]
 [-1.

1918 Cost :  2.6147032 
Prediction : 
 [[-0.8195473 ]
 [-0.71316725]
 [-1.0354989 ]
 [-1.3237698 ]
 [-1.2052364 ]
 [-1.0779433 ]
 [-1.5230298 ]
 [-1.0825269 ]]
1919 Cost :  2.6145122 
Prediction : 
 [[-0.819468 ]
 [-0.7130902]
 [-1.035434 ]
 [-1.3237188]
 [-1.2051766]
 [-1.0778854]
 [-1.5229897]
 [-1.0824876]]
1920 Cost :  2.6143217 
Prediction : 
 [[-0.81938875]
 [-0.713013  ]
 [-1.0353692 ]
 [-1.3236678 ]
 [-1.2051167 ]
 [-1.0778277 ]
 [-1.5229498 ]
 [-1.0824482 ]]
1921 Cost :  2.6141305 
Prediction : 
 [[-0.8193095]
 [-0.7129358]
 [-1.0353043]
 [-1.3236167]
 [-1.205057 ]
 [-1.0777698]
 [-1.5229098]
 [-1.0824089]]
1922 Cost :  2.6139398 
Prediction : 
 [[-0.8192302]
 [-0.7128585]
 [-1.0352395]
 [-1.3235656]
 [-1.2049972]
 [-1.0777118]
 [-1.5228697]
 [-1.0823696]]
1923 Cost :  2.613749 
Prediction : 
 [[-0.8191509]
 [-0.7127814]
 [-1.0351745]
 [-1.3235145]
 [-1.2049375]
 [-1.0776541]
 [-1.5228298]
 [-1.0823302]]
1924 Cost :  2.6135583 
Prediction : 
 [[-0.81907165]
 [-0.71270424]
 [-1